# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables use of the apache implementation of JSP.

[environment]
ee11

[depend]
ee11-servlet
ee11-annotations

[lib]
lib/ee11-apache-jsp/jakarta.el-api-6.0.1.jar
lib/ee11-apache-jsp/jakarta.servlet.jsp-api-4.0.0.jar
lib/ee11-apache-jsp/ecj-3.43.0.jar
lib/ee11-apache-jsp/mortbay-apache-el-11.0.10.1.jar
lib/ee11-apache-jsp/mortbay-apache-jsp-11.0.10.1.jar
lib/jetty-ee11-apache-jsp-${jetty.version}.jar

