# DO NOT EDIT THIS FILE - See: https://eclipse.dev/jetty/documentation/

[description]
Adds Sign-In with Ethereum (SIWE) authentication to the server.

[depend]
security

[files]
maven://org.bouncycastle/bcprov-jdk18on/${bouncycastle.version}|lib/bouncycastle/bcprov-jdk18on-${bouncycastle.version}.jar

[lib]
lib/jetty-ethereum-${jetty.version}.jar
lib/bouncycastle/bcprov-jdk18on-${bouncycastle.version}.jar

[ini]
bouncycastle.version?=1.83
jetty.webapp.addHiddenClasses+=,${jetty.base.uri}/lib/bouncycastle/
