# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables use of the apache implementation of JSP.

[environment]
ee10

[depend]
ee10-servlet
ee10-annotations

[lib]
lib/ee10-apache-jsp/jakarta.el-api-5.0.1.jar
lib/ee10-apache-jsp/jakarta.servlet.jsp-api-3.1.1.jar
lib/ee10-apache-jsp/ecj-3.43.0.jar
lib/ee10-apache-jsp/mortbay-apache-el-10.1.48.jar
lib/ee10-apache-jsp/mortbay-apache-jsp-10.1.48.jar
lib/jetty-ee10-apache-jsp-${jetty.version}.jar

