# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables the glassfish version of JSTL for all webapps.

[environment]
ee11

[depends]
ee11-apache-jsp

[lib]
lib/ee11-glassfish-jstl/jakarta.servlet.jsp.jstl-api-3.0.2.jar
lib/ee11-glassfish-jstl/wasp-4.0.0.jar
