# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables use of the apache implementation of JSP.

[environment]
ee8

[depend]
ee8-servlet
ee8-annotations

[lib]
lib/ee8-apache-jsp/ecj-3.43.0.jar
lib/ee8-apache-jsp/mortbay-apache-el-9.0.111.jar
lib/ee8-apache-jsp/mortbay-apache-jsp-9.0.111.jar
lib/jetty-ee8-apache-jsp-${jetty.version}.jar
