# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables the glassfish version of JSTL for all webapps.

[environment]
ee8

[ini]

[lib]
lib/ee8-glassfish-jstl/jakarta.servlet.jsp.jstl-api-1.2.7.jar
lib/ee8-glassfish-jstl/javax.servlet.jsp.jstl-1.2.5.jar
