# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables use of the apache implementation of JSP.

[environment]
ee9

[depend]
ee9-servlet
ee9-annotations

[lib]
lib/ee9-apache-jsp/ecj-3.43.0.jar
lib/ee9-apache-jsp/mortbay-apache-el-10.0.27.2.jar
lib/ee9-apache-jsp/mortbay-apache-jsp-10.0.27.2.jar
lib/jetty-ee9-apache-jsp-${jetty.version}.jar
