# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables the glassfish version of JSTL for all webapps.

[environment]
ee9

[lib]
lib/ee9-glassfish-jstl/jakarta.servlet.jsp.jstl-api-2.0.0.jar
lib/ee9-glassfish-jstl/jakarta.servlet.jsp.jstl-2.0.0.jar
