# DO NOT EDIT THIS FILE - See: https://jetty.org/docs/

[description]
Enables Annotation scanning for deployed web applications.

[environment]
ee9

[depend]
ee9-plus
annotations

[lib]
lib/jetty-ee9-annotations-${jetty.version}.jar
lib/ee9-annotations/jakarta.annotation-api-2.0.0.jar
